# Generated by Django 5.0.4 on 2024-04-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact8',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Employee8',
            new_name='Employee',
        ),
    ]
